import { useState } from "react";
import { Download, FileJson, Layout, FileText, CheckCircle2 } from "lucide-react";
import { useBuilderStore } from "@/store/useBuilderStore";
import { toast } from "sonner";
import JSZip from "jszip";

function safeParseJson(val: unknown): Record<string, any> {
  if (typeof val === "object" && val !== null) {
    return val as Record<string, any>;
  }
  if (typeof val === "string") {
    try {
      return JSON.parse(val);
    } catch (e) {
      console.warn("Failed to parse PWA asset JSON:", e);
      return {};
    }
  }
  return {};
}

export function ExportTab({ canEdit }: { canEdit: boolean }) {
  const execution = useBuilderStore((s) => s.execution);
  const pipeline = useBuilderStore((s) => s.pipeline);
  const [downloading, setDownloading] = useState(false);
  const [activeView, setActiveView] = useState<"preview" | "manifest" | "readme">("preview");

  const assets = execution?.pwa_assets as Record<string, string | object> | null;

  if (!execution || execution.status !== "completed" || !assets) {
    return (
      <div className="flex flex-col items-center justify-center h-[500px] text-muted-foreground bg-card border border-border rounded-lg">
        <Layout className="h-12 w-12 mb-4 opacity-20" />
        <p className="text-sm">No generated assets available.</p>
        <p className="text-xs mt-2">Run the pipeline successfully to preview and export the PWA.</p>
      </div>
    );
  }

  const indexHtml = typeof assets["index.html"] === "string" ? assets["index.html"] : "";
  const manifestObj = safeParseJson(assets["manifest.json"]);
  const contextObj = safeParseJson(assets["context.json"]);
  const swJs = typeof assets["service-worker.js"] === "string" ? assets["service-worker.js"] : (typeof assets["sw.js"] === "string" ? assets["sw.js"] : "");

  const summaryObj = {
    pipeline_id: pipeline?.id,
    execution_id: execution.id,
    generated_at: new Date().toISOString(),
    status: "success",
  };

  const readmeContent = `# ${pipeline?.title || "PWA App"}

This Progressive Web App (PWA) was generated by the Active Workflow Engine.

## Contents
- \`index.html\` - The main application UI and logic.
- \`manifest.json\` - PWA configuration.
- \`context.json\` - The context used to generate the app.
- \`execution-summary.json\` - Metadata about the generation process.
${swJs ? "- `service-worker.js` - Service worker for offline caching.\n" : ""}
## Usage
You can serve this folder using any static web server.
\`\`\`bash
npx serve .
\`\`\`
`;

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const zip = new JSZip();
      
      zip.file("index.html", indexHtml);
      zip.file("manifest.json", JSON.stringify(manifestObj, null, 2));
      zip.file("context.json", JSON.stringify(contextObj, null, 2));
      zip.file("execution-summary.json", JSON.stringify(summaryObj, null, 2));
      zip.file("README.md", readmeContent);
      if (swJs) {
        const swFileName = typeof assets["service-worker.js"] === "string" ? "service-worker.js" : "sw.js";
        zip.file(swFileName, swJs);
      }

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `pwa-export-${execution.id.slice(0, 8)}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success("PWA project ZIP downloaded successfully!");
    } catch (err: any) {
      console.error("Export failed:", err);
      toast.error(`Export failed: ${err?.message || String(err)}`);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
      {/* LEFT COLUMN: Controls & Assets */}
      <div className="lg:col-span-1 flex flex-col gap-4">
        {/* Export Summary Card */}
        <div className="bg-card border border-border rounded-lg p-5">
          <div className="flex items-center gap-2 mb-4">
            <CheckCircle2 className="h-5 w-5 text-green-500" />
            <h2 className="font-semibold text-base">Execution Successful</h2>
          </div>
          <p className="text-sm text-muted-foreground mb-6">
            Your PWA has been generated successfully and is ready for export.
          </p>
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="w-full bg-primary hover:bg-primary/90 text-primary-foreground py-2.5 rounded-md font-medium flex items-center justify-center gap-2 transition-colors disabled:opacity-60"
          >
            <Download className="h-4 w-4" />
            {downloading ? "Zipping..." : "Download ZIP"}
          </button>
        </div>

        {/* Generated Assets Table */}
        <div className="bg-card border border-border rounded-lg overflow-hidden flex-1">
          <div className="px-4 py-3 border-b border-border bg-muted/20">
            <h3 className="font-semibold text-sm">Generated Assets</h3>
          </div>
          <div className="divide-y divide-border">
            <div className="flex items-center justify-between px-4 py-2.5 text-sm">
              <span className="flex items-center gap-2 text-foreground">
                <Layout className="h-4 w-4 text-blue-500" /> index.html
              </span>
              <span className="text-xs text-muted-foreground">{indexHtml.length} bytes</span>
            </div>
            <div className="flex items-center justify-between px-4 py-2.5 text-sm">
              <span className="flex items-center gap-2 text-foreground">
                <FileJson className="h-4 w-4 text-amber-500" /> manifest.json
              </span>
              <span className="text-xs text-muted-foreground">JSON</span>
            </div>
            <div className="flex items-center justify-between px-4 py-2.5 text-sm">
              <span className="flex items-center gap-2 text-foreground">
                <FileJson className="h-4 w-4 text-emerald-500" /> context.json
              </span>
              <span className="text-xs text-muted-foreground">JSON</span>
            </div>
            {swJs && (
              <div className="flex items-center justify-between px-4 py-2.5 text-sm">
                <span className="flex items-center gap-2 text-foreground">
                  <FileText className="h-4 w-4 text-purple-500" /> {assets["service-worker.js"] ? "service-worker.js" : "sw.js"}
                </span>
                <span className="text-xs text-muted-foreground">{swJs.length} bytes</span>
              </div>
            )}
            <div className="flex items-center justify-between px-4 py-2.5 text-sm">
              <span className="flex items-center gap-2 text-foreground">
                <FileText className="h-4 w-4 text-muted-foreground" /> README.md
              </span>
              <span className="text-xs text-muted-foreground">Generated</span>
            </div>
          </div>
        </div>
      </div>

      {/* RIGHT COLUMN: Inspector */}
      <div className="lg:col-span-2 flex flex-col bg-card border border-border rounded-lg overflow-hidden h-[600px] lg:h-[700px]">
        {/* Toolbar */}
        <div className="flex items-center px-2 py-2 border-b border-border bg-muted/20 gap-1 overflow-x-auto">
          <button
            onClick={() => setActiveView("preview")}
            className={`px-3 py-1.5 text-sm rounded-md transition-colors flex items-center gap-2 whitespace-nowrap ${
              activeView === "preview" ? "bg-background shadow-sm border border-border/50 text-foreground" : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
            }`}
          >
            <Layout className="h-4 w-4" />
            Live Preview
          </button>
          <button
            onClick={() => setActiveView("manifest")}
            className={`px-3 py-1.5 text-sm rounded-md transition-colors flex items-center gap-2 whitespace-nowrap ${
              activeView === "manifest" ? "bg-background shadow-sm border border-border/50 text-foreground" : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
            }`}
          >
            <FileJson className="h-4 w-4" />
            Manifest
          </button>
          <button
            onClick={() => setActiveView("readme")}
            className={`px-3 py-1.5 text-sm rounded-md transition-colors flex items-center gap-2 whitespace-nowrap ${
              activeView === "readme" ? "bg-background shadow-sm border border-border/50 text-foreground" : "text-muted-foreground hover:bg-muted/50 hover:text-foreground"
            }`}
          >
            <FileText className="h-4 w-4" />
            README
          </button>
        </div>

        {/* Viewport */}
        <div className="flex-1 bg-muted/10 relative overflow-hidden flex flex-col">
          {activeView === "preview" && (
            <div className="flex-1 w-full flex items-center justify-center p-4 lg:p-8 overflow-y-auto">
              {/* Mobile device frame mockup */}
              <div className="w-[375px] h-[667px] bg-white rounded-[2rem] border-[8px] border-zinc-800 shadow-xl overflow-hidden relative shrink-0">
                {/* Notch */}
                <div className="absolute top-0 inset-x-0 h-6 bg-zinc-800 rounded-b-xl w-32 mx-auto z-10"></div>
                <iframe
                  srcDoc={indexHtml}
                  sandbox="allow-scripts allow-same-origin"
                  title="Live Preview"
                  className="w-full h-full border-0 bg-white"
                />
              </div>
            </div>
          )}

          {activeView === "manifest" && (
            <div className="flex-1 overflow-auto p-4">
              <pre className="text-sm mono text-foreground bg-background border border-border p-4 rounded-lg shadow-sm">
                {JSON.stringify(manifestObj, null, 2)}
              </pre>
            </div>
          )}

          {activeView === "readme" && (
            <div className="flex-1 overflow-auto p-4">
              <pre className="text-sm mono text-foreground bg-background border border-border p-4 rounded-lg shadow-sm whitespace-pre-wrap">
                {readmeContent}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
